
-- Master/lookup tables
CREATE TABLE IF NOT EXISTS public.livestock_groups (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  old_id INTEGER UNIQUE,
  name TEXT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT true,
  is_deleted BOOLEAN NOT NULL DEFAULT false,
  registered_user_id INTEGER, registered_date TIMESTAMPTZ,
  deleted_date TIMESTAMPTZ, deleted_user_id INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.livestock_types (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  old_id INTEGER UNIQUE,
  group_id BIGINT REFERENCES public.livestock_groups(id),
  old_group_id INTEGER,
  name TEXT NOT NULL,
  category_id INTEGER,
  is_active BOOLEAN NOT NULL DEFAULT true,
  is_deleted BOOLEAN NOT NULL DEFAULT false,
  registered_user_id INTEGER, registered_date TIMESTAMPTZ,
  deleted_date TIMESTAMPTZ, deleted_user_id INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.livestock_statuses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  old_id INTEGER UNIQUE,
  name TEXT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT true,
  is_deleted BOOLEAN NOT NULL DEFAULT false,
  registered_user_id INTEGER, registered_date TIMESTAMPTZ,
  deleted_date TIMESTAMPTZ, deleted_user_id INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.livestock_locations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  old_id INTEGER UNIQUE,
  name TEXT NOT NULL,
  code INTEGER,
  desirable_capacity INTEGER, max_capacity INTEGER,
  width NUMERIC, length NUMERIC,
  is_active BOOLEAN NOT NULL DEFAULT true,
  is_deleted BOOLEAN NOT NULL DEFAULT false,
  registered_user_id INTEGER, registered_date TIMESTAMPTZ,
  deleted_date TIMESTAMPTZ, deleted_user_id INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.sperm_companies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  old_id INTEGER UNIQUE,
  name TEXT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Extend existing sperms (already had id/name/code only)
ALTER TABLE public.sperms
  ADD COLUMN IF NOT EXISTS old_id INTEGER,
  ADD COLUMN IF NOT EXISTS father_id BIGINT,
  ADD COLUMN IF NOT EXISTS mother_id BIGINT,
  ADD COLUMN IF NOT EXISTS tpi INTEGER,
  ADD COLUMN IF NOT EXISTS pl NUMERIC,
  ADD COLUMN IF NOT EXISTS milk NUMERIC,
  ADD COLUMN IF NOT EXISTS sce NUMERIC,
  ADD COLUMN IF NOT EXISTS flc NUMERIC,
  ADD COLUMN IF NOT EXISTS udc NUMERIC,
  ADD COLUMN IF NOT EXISTS lnms NUMERIC,
  ADD COLUMN IF NOT EXISTS regno BIGINT,
  ADD COLUMN IF NOT EXISTS company_id BIGINT REFERENCES public.sperm_companies(id),
  ADD COLUMN IF NOT EXISTS old_company_id INTEGER,
  ADD COLUMN IF NOT EXISTS threshold NUMERIC,
  ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS registered_user_id INTEGER,
  ADD COLUMN IF NOT EXISTS registered_date TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS deleted_date TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS deleted_user_id INTEGER,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now();

CREATE UNIQUE INDEX IF NOT EXISTS ux_sperms_old_id ON public.sperms(old_id) WHERE old_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.sync_types (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  old_id INTEGER UNIQUE,
  name TEXT NOT NULL,
  medicine_and_times TEXT,
  inoculation_time NUMERIC,
  is_active BOOLEAN NOT NULL DEFAULT true,
  is_deleted BOOLEAN NOT NULL DEFAULT false,
  registered_user_id INTEGER, registered_date TIMESTAMPTZ,
  deleted_date TIMESTAMPTZ, deleted_user_id INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.sync_type_details (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  old_id INTEGER UNIQUE,
  sync_type_id BIGINT REFERENCES public.sync_types(id),
  old_sync_type_id INTEGER,
  medicine_id BIGINT,
  old_medicine_id INTEGER,
  sufficient_amount INTEGER,
  taking_medication_time NUMERIC,
  taking_medication_type_id INTEGER,
  is_medical BOOLEAN,
  description TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- History tables
CREATE TABLE IF NOT EXISTS public.cow_types (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  old_id INTEGER UNIQUE,
  cow_id BIGINT REFERENCES public.cows(id),
  old_cow_id INTEGER,
  type_id BIGINT REFERENCES public.livestock_types(id),
  old_type_id INTEGER,
  event_date TEXT,
  registered_user_id INTEGER, registered_date TIMESTAMPTZ,
  is_deleted BOOLEAN NOT NULL DEFAULT false,
  deleted_date TIMESTAMPTZ, deleted_user_id INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.cow_statuses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  old_id INTEGER UNIQUE,
  cow_id BIGINT REFERENCES public.cows(id),
  old_cow_id INTEGER,
  status_id BIGINT REFERENCES public.livestock_statuses(id),
  old_status_id INTEGER,
  event_date TEXT,
  registered_user_id INTEGER, registered_date TIMESTAMPTZ,
  is_deleted BOOLEAN NOT NULL DEFAULT false,
  deleted_date TIMESTAMPTZ, deleted_user_id INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.cow_locations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  old_id INTEGER UNIQUE,
  cow_id BIGINT REFERENCES public.cows(id),
  old_cow_id INTEGER,
  location_id BIGINT REFERENCES public.livestock_locations(id),
  old_location_id INTEGER,
  event_date TEXT,
  registered_user_id INTEGER, registered_date TIMESTAMPTZ,
  is_deleted BOOLEAN NOT NULL DEFAULT false,
  deleted_date TIMESTAMPTZ, deleted_user_id INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.cow_syncs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  old_id INTEGER UNIQUE,
  cow_id BIGINT REFERENCES public.cows(id),
  old_cow_id INTEGER,
  sync_type_id BIGINT REFERENCES public.sync_types(id),
  old_sync_type_id INTEGER,
  event_date TEXT,
  description TEXT,
  inoculation_date_time TEXT,
  status SMALLINT,
  stop_description TEXT,
  stop_date TEXT,
  stop_registered_user_id INTEGER,
  stop_registered_date TIMESTAMPTZ,
  registered_user_id INTEGER, registered_date TIMESTAMPTZ,
  is_deleted BOOLEAN NOT NULL DEFAULT false,
  deleted_date TIMESTAMPTZ, deleted_user_id INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.cow_sync_details (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  old_id INTEGER UNIQUE,
  cow_sync_id BIGINT REFERENCES public.cow_syncs(id),
  old_cow_sync_id INTEGER,
  date_time TEXT,
  medicine_id BIGINT,
  old_medicine_id INTEGER,
  injector_user_id INTEGER,
  injection_date_time TEXT,
  status SMALLINT,
  injection_description TEXT,
  injection_registered_user_id INTEGER,
  injection_registered_date TIMESTAMPTZ,
  registered_user_id INTEGER, registered_date TIMESTAMPTZ,
  is_deleted BOOLEAN NOT NULL DEFAULT false,
  deleted_date TIMESTAMPTZ, deleted_user_id INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Extend cows
ALTER TABLE public.cows
  ADD COLUMN IF NOT EXISTS old_id INTEGER,
  ADD COLUMN IF NOT EXISTS date_of_birth TEXT,
  ADD COLUMN IF NOT EXISTS father_id BIGINT,
  ADD COLUMN IF NOT EXISTS mother_id BIGINT,
  ADD COLUMN IF NOT EXISTS birth_weight NUMERIC,
  ADD COLUMN IF NOT EXISTS type_mother_inoculation BOOLEAN,
  ADD COLUMN IF NOT EXISTS father_sperm_id BIGINT REFERENCES public.sperms(id),
  ADD COLUMN IF NOT EXISTS old_father_sperm_id INTEGER,
  ADD COLUMN IF NOT EXISTS last_location_id BIGINT REFERENCES public.livestock_locations(id),
  ADD COLUMN IF NOT EXISTS old_last_location_id INTEGER,
  ADD COLUMN IF NOT EXISTS last_status_id BIGINT REFERENCES public.livestock_statuses(id),
  ADD COLUMN IF NOT EXISTS old_last_status_id INTEGER,
  ADD COLUMN IF NOT EXISTS last_type_id BIGINT REFERENCES public.livestock_types(id),
  ADD COLUMN IF NOT EXISTS old_last_type_id INTEGER,
  ADD COLUMN IF NOT EXISTS number_of_births INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS number_of_daughter INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS number_of_son INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS number_of_deaths INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS birth_status SMALLINT,
  ADD COLUMN IF NOT EXISTS place_of_birth SMALLINT,
  ADD COLUMN IF NOT EXISTS description TEXT,
  ADD COLUMN IF NOT EXISTS last_fertility_status_date TEXT,
  ADD COLUMN IF NOT EXISTS last_location_date TEXT,
  ADD COLUMN IF NOT EXISTS last_type_date TEXT,
  ADD COLUMN IF NOT EXISTS last_status_date TEXT,
  ADD COLUMN IF NOT EXISTS last_birth_date TEXT,
  ADD COLUMN IF NOT EXISTS is_pregnancy BOOLEAN,
  ADD COLUMN IF NOT EXISTS current_live_weight NUMERIC,
  ADD COLUMN IF NOT EXISTS current_meat_weight NUMERIC,
  ADD COLUMN IF NOT EXISTS existence_description TEXT,
  ADD COLUMN IF NOT EXISTS existence_date TEXT,
  ADD COLUMN IF NOT EXISTS last_erotic_date TEXT,
  ADD COLUMN IF NOT EXISTS last_inoculation_date TEXT,
  ADD COLUMN IF NOT EXISTS last_pregnancy_date TEXT,
  ADD COLUMN IF NOT EXISTS last_abortion_date TEXT,
  ADD COLUMN IF NOT EXISTS last_dry_date TEXT,
  ADD COLUMN IF NOT EXISTS last_rinse_date TEXT,
  ADD COLUMN IF NOT EXISTS last_clean_test_date TEXT,
  ADD COLUMN IF NOT EXISTS last_sync_date TEXT,
  ADD COLUMN IF NOT EXISTS last_out_abortion_date TEXT,
  ADD COLUMN IF NOT EXISTS last_out_birth_date TEXT,
  ADD COLUMN IF NOT EXISTS last_out_dry_date TEXT,
  ADD COLUMN IF NOT EXISTS last_out_period INTEGER,
  ADD COLUMN IF NOT EXISTS last_period INTEGER,
  ADD COLUMN IF NOT EXISTS last_hoof_trimming_date TEXT,
  ADD COLUMN IF NOT EXISTS last_hoof_trimming_details TEXT,
  ADD COLUMN IF NOT EXISTS last_magnet_eating_date TEXT,
  ADD COLUMN IF NOT EXISTS last_magnet_eating_details TEXT,
  ADD COLUMN IF NOT EXISTS last_burn_horn_date TEXT,
  ADD COLUMN IF NOT EXISTS last_burn_horn_details TEXT,
  ADD COLUMN IF NOT EXISTS start_date_of_calf_milk TEXT,
  ADD COLUMN IF NOT EXISTS end_date_of_calf_milk TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS ux_cows_old_id ON public.cows(old_id) WHERE old_id IS NOT NULL;

-- Indexes
CREATE INDEX IF NOT EXISTS ix_livestock_types_group_id ON public.livestock_types(group_id);
CREATE INDEX IF NOT EXISTS ix_livestock_groups_active ON public.livestock_groups(is_active) WHERE is_deleted = false;
CREATE INDEX IF NOT EXISTS ix_livestock_types_active ON public.livestock_types(is_active) WHERE is_deleted = false;
CREATE INDEX IF NOT EXISTS ix_livestock_statuses_active ON public.livestock_statuses(is_active) WHERE is_deleted = false;
CREATE INDEX IF NOT EXISTS ix_livestock_locations_active ON public.livestock_locations(is_active) WHERE is_deleted = false;
CREATE INDEX IF NOT EXISTS ix_sperms_company ON public.sperms(company_id);
CREATE INDEX IF NOT EXISTS ix_sperms_active ON public.sperms(is_active) WHERE is_deleted = false;
CREATE INDEX IF NOT EXISTS ix_sync_type_details_sync ON public.sync_type_details(sync_type_id);
CREATE INDEX IF NOT EXISTS ix_cow_types_cow ON public.cow_types(cow_id);
CREATE INDEX IF NOT EXISTS ix_cow_types_old_cow ON public.cow_types(old_cow_id);
CREATE INDEX IF NOT EXISTS ix_cow_types_event_date ON public.cow_types(event_date);
CREATE INDEX IF NOT EXISTS ix_cow_statuses_cow ON public.cow_statuses(cow_id);
CREATE INDEX IF NOT EXISTS ix_cow_statuses_old_cow ON public.cow_statuses(old_cow_id);
CREATE INDEX IF NOT EXISTS ix_cow_statuses_event_date ON public.cow_statuses(event_date);
CREATE INDEX IF NOT EXISTS ix_cow_locations_cow ON public.cow_locations(cow_id);
CREATE INDEX IF NOT EXISTS ix_cow_locations_old_cow ON public.cow_locations(old_cow_id);
CREATE INDEX IF NOT EXISTS ix_cow_locations_event_date ON public.cow_locations(event_date);
CREATE INDEX IF NOT EXISTS ix_cow_syncs_cow ON public.cow_syncs(cow_id);
CREATE INDEX IF NOT EXISTS ix_cow_syncs_old_cow ON public.cow_syncs(old_cow_id);
CREATE INDEX IF NOT EXISTS ix_cow_syncs_event_date ON public.cow_syncs(event_date);
CREATE INDEX IF NOT EXISTS ix_cow_sync_details_sync ON public.cow_sync_details(cow_sync_id);

-- updated_at triggers
DO $$
DECLARE t TEXT;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'livestock_groups','livestock_types','livestock_statuses','livestock_locations',
    'sperm_companies','sync_types','sync_type_details',
    'cow_types','cow_statuses','cow_locations','cow_syncs','cow_sync_details'
  ] LOOP
    EXECUTE format('DROP TRIGGER IF EXISTS trg_%I_updated_at ON public.%I;', t, t);
    EXECUTE format(
      'CREATE TRIGGER trg_%I_updated_at BEFORE UPDATE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();',
      t, t
    );
  END LOOP;
END$$;

-- RLS — permissive authenticated policies
DO $$
DECLARE t TEXT;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'livestock_groups','livestock_types','livestock_statuses','livestock_locations',
    'sperm_companies','sync_types','sync_type_details',
    'cow_types','cow_statuses','cow_locations','cow_syncs','cow_sync_details'
  ] LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY;', t);
    EXECUTE format('DROP POLICY IF EXISTS "auth_select_%s" ON public.%I;', t, t);
    EXECUTE format('DROP POLICY IF EXISTS "auth_insert_%s" ON public.%I;', t, t);
    EXECUTE format('DROP POLICY IF EXISTS "auth_update_%s" ON public.%I;', t, t);
    EXECUTE format('DROP POLICY IF EXISTS "auth_delete_%s" ON public.%I;', t, t);
    EXECUTE format('CREATE POLICY "auth_select_%s" ON public.%I FOR SELECT TO authenticated USING (true);', t, t);
    EXECUTE format('CREATE POLICY "auth_insert_%s" ON public.%I FOR INSERT TO authenticated WITH CHECK (true);', t, t);
    EXECUTE format('CREATE POLICY "auth_update_%s" ON public.%I FOR UPDATE TO authenticated USING (true) WITH CHECK (true);', t, t);
    EXECUTE format('CREATE POLICY "auth_delete_%s" ON public.%I FOR DELETE TO authenticated USING (true);', t, t);
  END LOOP;
END$$;
