
-- Certificates table
CREATE TABLE public.certificates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  doc_type TEXT NOT NULL DEFAULT 'گواهینامه',
  issuer TEXT,
  doc_number TEXT,
  issue_date_shamsi TEXT,
  expiry_date_shamsi TEXT,
  description TEXT,
  image_url TEXT,
  attachment_urls TEXT[] NOT NULL DEFAULT '{}',
  renewal_lead_time TEXT,
  renewal_custom_date_shamsi TEXT,
  renewal_ticket_id BIGINT,
  renewal_ticket_created_at TIMESTAMPTZ,
  created_by TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.certificates ENABLE ROW LEVEL SECURITY;

-- Permissive policies matching the rest of this project's pattern
CREATE POLICY "certificates_select_all" ON public.certificates FOR SELECT USING (true);
CREATE POLICY "certificates_insert_all" ON public.certificates FOR INSERT WITH CHECK (true);
CREATE POLICY "certificates_update_all" ON public.certificates FOR UPDATE USING (true);
CREATE POLICY "certificates_delete_all" ON public.certificates FOR DELETE USING (true);

CREATE TRIGGER update_certificates_updated_at
BEFORE UPDATE ON public.certificates
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();

-- Realtime
ALTER TABLE public.certificates REPLICA IDENTITY FULL;
ALTER PUBLICATION supabase_realtime ADD TABLE public.certificates;

-- Storage bucket
INSERT INTO storage.buckets (id, name, public) VALUES ('certificates', 'certificates', true)
ON CONFLICT (id) DO NOTHING;

CREATE POLICY "certificates_bucket_public_read" ON storage.objects
FOR SELECT USING (bucket_id = 'certificates');

CREATE POLICY "certificates_bucket_insert" ON storage.objects
FOR INSERT WITH CHECK (bucket_id = 'certificates');

CREATE POLICY "certificates_bucket_update" ON storage.objects
FOR UPDATE USING (bucket_id = 'certificates');

CREATE POLICY "certificates_bucket_delete" ON storage.objects
FOR DELETE USING (bucket_id = 'certificates');
