// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gwwryrdrbmhifhfdmkph.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd3d3J5cmRyYm1oaWZoZmRta3BoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYwMDkxNjMsImV4cCI6MjA5MTU4NTE2M30.ZZjJKQjmx8tkEcExL8LnbPWgRPbH69DqkXy-h_IhqSU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});